// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnozvuemtvesgpubpeqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRub3p2dWVtdHZlc2dwdWJwZXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIyNzY1MDgsImV4cCI6MjA5Nzg1MjUwOH0.92VabW4-4lYMJ-de0kr2egviP-9ppRsft5jCNuelzdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});